// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfupA1nceaiKaWzPP4EYNlV633D59SSbg',
    appId: '1:850944259113:web:27f9360cd820fcaeddd838',
    messagingSenderId: '850944259113',
    projectId: 'carparks-c719c',
    authDomain: 'carparks-c719c.firebaseapp.com',
    databaseURL: 'https://carparks-c719c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'carparks-c719c.firebasestorage.app',
    measurementId: 'G-BN85GPSFHT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLyjAqsWEuirarY5fkmAdDbmsnX6pkRYA',
    appId: '1:850944259113:android:5d5127e3e21fa5c2ddd838',
    messagingSenderId: '850944259113',
    projectId: 'carparks-c719c',
    databaseURL: 'https://carparks-c719c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'carparks-c719c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDf2DsUfQZAclyGrujoaLhPFEpfbZD4Nzo',
    appId: '1:850944259113:ios:57f81c619396f858ddd838',
    messagingSenderId: '850944259113',
    projectId: 'carparks-c719c',
    databaseURL: 'https://carparks-c719c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'carparks-c719c.firebasestorage.app',
    iosBundleId: 'com.example.testApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDf2DsUfQZAclyGrujoaLhPFEpfbZD4Nzo',
    appId: '1:850944259113:ios:57f81c619396f858ddd838',
    messagingSenderId: '850944259113',
    projectId: 'carparks-c719c',
    databaseURL: 'https://carparks-c719c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'carparks-c719c.firebasestorage.app',
    iosBundleId: 'com.example.testApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfupA1nceaiKaWzPP4EYNlV633D59SSbg',
    appId: '1:850944259113:web:b3026a81f8839547ddd838',
    messagingSenderId: '850944259113',
    projectId: 'carparks-c719c',
    authDomain: 'carparks-c719c.firebaseapp.com',
    databaseURL: 'https://carparks-c719c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'carparks-c719c.firebasestorage.app',
    measurementId: 'G-Q0ZC3FEKBZ',
  );

}